trigger:
  branches:
    exclude:
      - '*'

pr:
  branches:
    include:
      - '*'

jobs:
- job: Build
  displayName: 'Build Job'
  pool:
    name: RAYYANMINHAJ
  steps:
  - script: echo 'Building the code'
    displayName: 'Build Step'